import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV file of initial conditions generated by N-GenIC
df = pd.read_csv("initial_conditions.csv")  # update name if needed

# Extract positions and velocities
x = df['x']
vx = df['vx']

# Plot phase-space diagram
plt.figure(figsize=(8,6))
plt.hexbin(x, vx, gridsize=300, cmap='plasma', bins='log')
plt.xlabel('x [Mpc/h]')
plt.ylabel('v_x [km/s]')
plt.title('Phase-Space Diagram: x vs. v_x')
plt.colorbar(label='log(N)')
plt.tight_layout()
plt.show()
