# Define the virtual environment directory
VENV := venv

# Default target
all: install run

# Create a virtual environment
venv:
	python3 -m venv $(VENV)

# Install dependencies from requirements.txt
install: venv
	$(VENV)/bin/pip install -r requirements.txt

# Run the main script
run:
	$(VENV)/bin/python custom_power_spectrum.py

# Run tests
test:
	$(VENV)/bin/pytest tests/

# Clean up virtual environment and compiled Python files
clean:
	rm -rf $(VENV) __pycache__
	find . -name "*.pyc" -delete
